### ISSUE TITLE
Few things required before I use this in a serious project

### ISSUE THREAD

**Issue by arpanpreneur** [davmik2601/typeorm-scoped#1]
Congratulations on your first issue in this repository. You have created a really important library, to say the least. I am interested in this library primarily to implement row-based multi-tenancy in a SaaS app using NestJS. Here are a few questions for you.

1. Is this project used by you in a serious production codebase?
2. How do you pass dynamic parameters to your scope filter? I need to pass my current logged-in user to it.
3. Is there a way we can apply save scopes too? For example, whenever a user saves something, the tenantId column is set.
4. How can we collaborate on this project so that it becomes useful for others?

**Comment by davmik2601** [comment]
Dear @ArpanKIIT2017 , 

1. this is a new package․ But I have used it and still use (now I am using) it in several projects (NestJS).
2. my filters (scopes) have not parametrs, you are calling scops like  `userRepository.scoped("females", "adultUsers").find(...)`, i․e․ as string in scope (i.e. scopeName (key))․
3. about save. If I understood correctly, it is about saving any entity instance․  I did not work on them. We need to think about how to use or create features during save. Is there a need for it? This package works pretty well for select requests.
4. if you have ideas to improve the code or new features, you can clone my code, test it on you - on local. if you have new solutions, I will listen with great pleasure and give you access to make some changes in this Repository.

In the end, I will add that I am using this package in multi-tenant project, where I have tenant table, and other tables connected to it. But I created and using this package only for any selects, and like sql views. (not for tenant).

Thanks.

**Comment by arpanpreneur** [comment]
@davmik2601 Thanks for your prompt reply. Just curious, how are you managing the shared db multi-tenancy currently?

**Comment by davmik2601** [comment]
> @davmik2601 Thanks for your prompt reply. Just curious, how are you managing the shared db multi-tenancy currently?

@ArpanKIIT2017 , on high level in code I created BaseRepositoy extends Repository, who has findWithTenant, findOneWithTenant, saveWithTenant methods, and they work with tenant...  And also I have TenantInterceptor, who set tenant in ContextService, And I use it in BaseRepository tenanty declared methods.

I think, after any time (if i'm free), i can add new features for this.

See this.

![image](https://github.com/davmik2601/typeorm-scoped/assets/89848236/4c9d4bf7-d998-448d-a707-5959de5e2b3b)

![image](https://github.com/davmik2601/typeorm-scoped/assets/89848236/3bfa3ea6-0220-4c5e-8702-e35cf97ec554)

**Comment by davmik2601** [comment]
![image](https://github.com/davmik2601/typeorm-scoped/assets/89848236/cb4a28aa-76cc-4601-b255-4f4ce1937af7)
![image](https://github.com/davmik2601/typeorm-scoped/assets/89848236/c1f4a4ff-f705-4885-b611-b356792bb03d)

> @davmik2601 Thanks for your prompt reply. Just curious, how are you managing the shared db multi-tenancy currently?

@ArpanKIIT2017 . You can see this images.

**Comment by arpanpreneur** [comment]
Awesome implementation.

**Comment by davmik2601** [comment]
Because what you wrote are features related to save. I will close this issue. Such features will be added later. Thanks

**Comment by davmik2601** [comment]
Because what you wrote are features related to save. I will close this issue. Such features will be added later. Thanks
